[package]
name = "genpixlib"
version = "0.1.0"
authors = ["Dominic Wassef <dominic@wassef.dev>"]

[dependencies]
image = "0.10.4"
num-complex = "0.1.35"
rand = "0.3.15"

[dev-dependencies]
stainless = "*"